# Generated by Django 5.0.6 on 2024-05-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot')),
            ],
            options={
                'unique_together': {('patient', 'doctor', 'date', 'time_slot')},
            },
        ),
    ]
